### ISSUE TITLE
Incorrect filename in merge step in HPC.REPmask

### ISSUE THREAD

**Issue by godotgildor** [thegenemyers/DAMASKER#1]
I am running HPC.REPmask on a database with 68 blocks and asking REPmask to consider 3 blocks at a time (-g3).  After the daligner stage comes the stage of LAsort and LAmerge commands.  At first glance it looks like the output names for the LAmerge steps for blocks 67 and 68 are incorrect.  Below is a copy of the commands created for blocks 66, 67, and 68.  Note that the output name for the LAmerge step for block 66 follows the form **L1.66.3** (as do the outputs for blocks 1-65) while the output for blocks 67 and 68 follow the form **raw_reads.R3.67**.  Moreover, the exact same output names for blocks 67 and 68 appear twice, implying that one of them will be overwritten.

`LAsort raw_reads.66.raw_reads.64.C0 raw_reads.66.raw_reads.64.N0 raw_reads.66.raw_reads.64.C1 raw_reads.66.raw_reads.64.N1 raw_reads.66.raw_reads.64.C2 raw_reads.66.raw_reads.64.N2 raw_reads.66.raw_reads.64.C3 raw_reads.66.raw_reads.64.N3 && LAmerge L1.66.1 raw_reads.66.raw_reads.64.C0.S raw_reads.66.raw_reads.64.N0.S raw_reads.66.raw_reads.64.C1.S raw_reads.66.raw_reads.64.N1.S raw_reads.66.raw_reads.64.C2.S raw_reads.66.raw_reads.64.N2.S raw_reads.66.raw_reads.64.C3.S raw_reads.66.raw_reads.64.N3.S
LAsort raw_reads.66.raw_reads.65.C0 raw_reads.66.raw_reads.65.N0 raw_reads.66.raw_reads.65.C1 raw_reads.66.raw_reads.65.N1 raw_reads.66.raw_reads.65.C2 raw_reads.66.raw_reads.65.N2 raw_reads.66.raw_reads.65.C3 raw_reads.66.raw_reads.65.N3 && LAmerge L1.66.2 raw_reads.66.raw_reads.65.C0.S raw_reads.66.raw_reads.65.N0.S raw_reads.66.raw_reads.65.C1.S raw_reads.66.raw_reads.65.N1.S raw_reads.66.raw_reads.65.C2.S raw_reads.66.raw_reads.65.N2.S raw_reads.66.raw_reads.65.C3.S raw_reads.66.raw_reads.65.N3.S
LAsort raw_reads.66.raw_reads.66.C0 raw_reads.66.raw_reads.66.N0 raw_reads.66.raw_reads.66.C1 raw_reads.66.raw_reads.66.N1 raw_reads.66.raw_reads.66.C2 raw_reads.66.raw_reads.66.N2 raw_reads.66.raw_reads.66.C3 raw_reads.66.raw_reads.66.N3 && LAmerge L1.66.3 raw_reads.66.raw_reads.66.C0.S raw_reads.66.raw_reads.66.N0.S raw_reads.66.raw_reads.66.C1.S raw_reads.66.raw_reads.66.N1.S raw_reads.66.raw_reads.66.C2.S raw_reads.66.raw_reads.66.N2.S raw_reads.66.raw_reads.66.C3.S raw_reads.66.raw_reads.66.N3.S
LAsort raw_reads.67.raw_reads.67.C0 raw_reads.67.raw_reads.67.N0 raw_reads.67.raw_reads.67.C1 raw_reads.67.raw_reads.67.N1 raw_reads.67.raw_reads.67.C2 raw_reads.67.raw_reads.67.N2 raw_reads.67.raw_reads.67.C3 raw_reads.67.raw_reads.67.N3 && LAmerge raw_reads.R3.67 raw_reads.67.raw_reads.67.C0.S raw_reads.67.raw_reads.67.N0.S raw_reads.67.raw_reads.67.C1.S raw_reads.67.raw_reads.67.N1.S raw_reads.67.raw_reads.67.C2.S raw_reads.67.raw_reads.67.N2.S raw_reads.67.raw_reads.67.C3.S raw_reads.67.raw_reads.67.N3.S
LAsort raw_reads.67.raw_reads.68.C0 raw_reads.67.raw_reads.68.N0 raw_reads.67.raw_reads.68.C1 raw_reads.67.raw_reads.68.N1 raw_reads.67.raw_reads.68.C2 raw_reads.67.raw_reads.68.N2 raw_reads.67.raw_reads.68.C3 raw_reads.67.raw_reads.68.N3 && LAmerge raw_reads.R3.68 raw_reads.67.raw_reads.68.C0.S raw_reads.67.raw_reads.68.N0.S raw_reads.67.raw_reads.68.C1.S raw_reads.67.raw_reads.68.N1.S raw_reads.67.raw_reads.68.C2.S raw_reads.67.raw_reads.68.N2.S raw_reads.67.raw_reads.68.C3.S raw_reads.67.raw_reads.68.N3.S
LAsort raw_reads.68.raw_reads.67.C0 raw_reads.68.raw_reads.67.N0 raw_reads.68.raw_reads.67.C1 raw_reads.68.raw_reads.67.N1 raw_reads.68.raw_reads.67.C2 raw_reads.68.raw_reads.67.N2 raw_reads.68.raw_reads.67.C3 raw_reads.68.raw_reads.67.N3 && LAmerge raw_reads.R3.67 raw_reads.68.raw_reads.67.C0.S raw_reads.68.raw_reads.67.N0.S raw_reads.68.raw_reads.67.C1.S raw_reads.68.raw_reads.67.N1.S raw_reads.68.raw_reads.67.C2.S raw_reads.68.raw_reads.67.N2.S raw_reads.68.raw_reads.67.C3.S raw_reads.68.raw_reads.67.N3.S
LAsort raw_reads.68.raw_reads.68.C0 raw_reads.68.raw_reads.68.N0 raw_reads.68.raw_reads.68.C1 raw_reads.68.raw_reads.68.N1 raw_reads.68.raw_reads.68.C2 raw_reads.68.raw_reads.68.N2 raw_reads.68.raw_reads.68.C3 raw_reads.68.raw_reads.68.N3 && LAmerge raw_reads.R3.68 raw_reads.68.raw_reads.68.C0.S raw_reads.68.raw_reads.68.N0.S raw_reads.68.raw_reads.68.C1.S raw_reads.68.raw_reads.68.N1.S raw_reads.68.raw_reads.68.C2.S raw_reads.68.raw_reads.68.N2.S raw_reads.68.raw_reads.68.C3.S raw_reads.68.raw_reads.68.N3.S
`

Later in the script, there is reference to the files **L1.67.1**, **L1.67.2**, **L1.68.1**, **L1.68.2**, but these do not exist due to the above different naming scheme for these blocks.

`LAmerge raw_reads.R3.66 L1.66.1 L1.66.2 L1.66.3
LAmerge raw_reads.R3.67 L1.67.1 L1.67.2
LAmerge raw_reads.R3.68 L1.68.1 L1.68.2`

I'm attaching the full output of HPC.REPmask.

[HPC.REPmask.txt](https://github.com/thegenemyers/DAMASKER/files/233923/HPC.REPmask.txt)

**Comment by thegenemyers** [comment]
Hi Brett,

```
Definitely a mistake, I'll fix it soom and email you back when I 
```

commit the fix.

```
In the meantime, find your specific script appropriately edited so 
```

that it will work.

```
One thing to note is that HPC.REPmask generates an incremental 
```

script, i.e.
doing say HPC.REPmask -g3 DB 1-10, and then HPC.REPmask -g3 DB 11-68
later, will operate correctly, but it means that REPmask is not run on 
the last
group of 3 if it is not a full group.  So in your case, you would have 
to finish
it off with explicit calls to REPmask for DB.67 and DB.68, noting that 
the LAs
are only for a 2 block by 2 block comparison (and hence repeats will not 
stack
up as high as a 3 block by 3 block comparison), so you should adjust -c 
downwards
by 2/3rds, e.g. in your case to 10.

```
-- Gene
```

**Comment by godotgildor** [comment]
Thanks Gene.  I hadn't thought about the incomplete group issue, but what
you said makes sense.  Thanks for pointing that out to me.

Also, just as an aside, when adapting this to run on the cloud, I am
basically doing one group per worker node.  The script is written in such a
way that this is a pretty easy and straight forward way to split up the
work.  In the case of my sample script with 3 blocks per group, I am taking
groups of 3 daligner commands, then the LAsort and LAmerge command that
operate on the blocks that make up that group and running those on the same
worker.  The only hiccup is when it comes to the REPmask command.  The
REPmask command in my generated script operates on 4 blocks at a time, so
the first command operates on outputs from blocks 1, 2, 3, and 4, whereas
the first worker only has the output for blocks 1, 2, and 3.  It would be
nice for me if the REPmask commands grouped blocks in groups of -g (in this
example 3) so that each worker would then 1) run the daligners 2) run the
LAsort and LAmerge commands 3) run REPmask, and the return back the mask
tracks for that group.  Then there would be a final gather step which could
take those tracks and run the cat command.  It's not a big deal, for now
I'll probably just create my own REPmask commands to call on the groups
rather than take the commands from the script, but I wanted to let you know
one somewhat particular use pattern.

-Brett

On Mon, Apr 25, 2016 at 3:45 AM, Eugene W Myers Jr <notifications@github.com

**Comment by thegenemyers** [comment]
Brett,

```
 I have committed a new version of HPC.REPmask(.c) at Github.

 It fixes the bug reported in this email.

 It also divides the REPmask and final rm commands so that they can be
```

assigned in groups to a cloud node as per your follow on request.

```
 In thinking about the issue more deeply, I came up with a new 
```

script/scheme
that handles the issue of an incomplete last group so that you (the 
user) don't
have to be aware of it or take any action.  Basically what I realized is 
that what's
important is that every block is compared against g other blocks. As 
before the
blocks are compared in groups of g up to possibly a few remnants, which are
now compared against the last g blocks.  This is much cleaner as it 
leaves no
intermediate files for the next batch job in an incremental process, and 
the -c
level specified for REPmask is good for all the .las produced for each 
block.  The
only restriction is that the number of blocks in the data base must be 

> = -g and if
> you call HPC.REPmask -cx -gs DB a-b then b must be >= s.

```
 Hopefully this closes the issue satisfactorily.

 Cheers,
      Gene
```
