### ISSUE TITLE
-c value for DASqv

### ISSUE THREAD

**Issue by mictadlo** [thegenemyers/DAMASKER#10]
Hi,
How to determine the best `-c` value for DASqv? Is it the coverage (seq_lengths / genome_size) or do I have to multiply it e.g. 3?

Thank you in advance

Michal

**Comment by thegenemyers** [comment]
Dear Michal,

     It should be whatever you think the effective coverage of the 
genome is,
i.e. total seq data / estimated genome size, as you wrote.  Problem is often
estimates of genome size are often very far off and in fact 10-15% of the
Pacbio read data is basically junk.

     I did add a couple of new commands, DAScover and REPcover, in the 
latest
upload to github for the scrubber module.  Running DAScover will give you
the average *effective* coverage of reads, that is it is the average 
coverage of
the good parts of the reads by other reads.  This is a good number to 
use for -c
to DASqv.

     In a planned future version of the scrubber module, the parameters 
-c for DASqv
and the parameters -g and -b for DAStrim will become optional, with the 
pipeline
itself will take care of figuring out what these parameters should be.

    -- Gene

**Comment by mictadlo** [comment]
Thank you, could you please make -x in DASedit optional so the pipeline itself will take care of figuring out what this parameter should be?
