### ISSUE TITLE
HPC.REPmask generates wrong order of arguments for LAmerge and LAcheck

### ISSUE THREAD

**Issue by marcopessoa** [thegenemyers/DAMASKER#12]
I am trying to run DAMASKER before DAScover and the current commit of HPC.REPmask is giving me the wrong order of arguments for LAmerge && LAcheck. In addition, it repeats the same last argument of LAcheck in the entire list of commands.

This is what I get:
LAmerge  -v test_db.R2.1 test_db test_db.1.test_db.@1-2 && LAcheck -vS test_db.R2.2
LAmerge  -v test_db.R2.2 test_db test_db.2.test_db.@1-2 && LAcheck -vS test_db.R2.2
LAmerge  -v test_db.R2.3 test_db test_db.3.test_db.@3-4 && LAcheck -vS test_db.R2.2
...

And I guess this would be the expected behavior:
LAmerge  -v test_db.R2.1 test_db.1.test_db.@1-2 && LAcheck -vS test_db test_db.R2.1
LAmerge  -v test_db.R2.2 test_db.1.test_db.@1-2 && LAcheck -vS test_db test_db.R2.2
LAmerge  -v test_db.R2.3 test_db.1.test_db.@3-4 && LAcheck -vS test_db test_db.R2.3

I found this section in the HPC.REPmask.c file that seems to be causing this:

Line 571:

```
fprintf(out,"LAmerge ");
            if (VON)
              fprintf(out," -v");
            if (DON)
              fprintf(out," temp%d/%s.R%d.%d",i,root,SPAN,i);
            else
              fprintf(out," %s.R%d.%d",root,SPAN,i);
            if (usepath)
              fprintf(out," %s/%s",pwd,root);
            else
              fprintf(out," %s",root);
            if (DON)
              fprintf(out," temp%d/%s.%d.%s.%c%d-%d",i,root,i,root,BLOCK_SYMBOL,base,base+(SPAN-1));
            else
              fprintf(out," %s.%d.%s.%c%d-%d",root,i,root,BLOCK_SYMBOL,base,base+(SPAN-1));

            fprintf(out," && LAcheck -vS");
            if (DON)
              fprintf(out," temp%d/%s.R%d.%d",i,root,SPAN,i);
            else
              fprintf(out," %s.R%d.%d",root,SPAN,j);
```

I changed it to:

 ```
 fprintf(out,"LAmerge ");
            if (VON)
              fprintf(out," -v");
            if (DON)
              fprintf(out," temp%d/%s.R%d.%d",i,root,SPAN,i);
            else
              fprintf(out," %s.R%d.%d",root,SPAN,i);
            if (DON)
              fprintf(out," temp%d/%s.%d.%s.%c%d-%d",i,root,i,root,BLOCK_SYMBOL,base,base+(SPAN-1));
            else
              fprintf(out," %s.%d.%s.%c%d-%d",root,i,root,BLOCK_SYMBOL,base,base+(SPAN-1));

            fprintf(out," && LAcheck -vS");
             if (usepath)
              fprintf(out," %s/%s",pwd,root);
            else
              fprintf(out," %s",root);
            if (DON)
              fprintf(out," temp%d/%s.R%d.%d",i,root,SPAN,i);
            else
              fprintf(out," %s.R%d.%d",root,SPAN,i);
```

and it seems to fix it.

**Comment by thegenemyers** [comment]
Yep, sorry.  Your corrections were correct.  I committed a new version with your fixes in.
Thanks,  Gene
