### ISSUE TITLE
Leftover files after HPC.REPmask

### ISSUE THREAD

**Issue by gt1** [thegenemyers/DAMASKER#5]
The file removal section misses some files.  I have a database with 604 blocks. Running the program with option -g10 leaves behind the files

reads.595.reads.601.las
reads.595.reads.602.las
reads.595.reads.603.las
reads.595.reads.604.las
reads.596.reads.601.las
reads.596.reads.602.las
reads.596.reads.603.las
reads.596.reads.604.las
reads.597.reads.601.las
reads.597.reads.602.las
reads.597.reads.603.las
reads.597.reads.604.las
reads.598.reads.601.las
reads.598.reads.602.las
reads.598.reads.603.las
reads.598.reads.604.las
reads.599.reads.601.las
reads.599.reads.602.las
reads.599.reads.603.las
reads.599.reads.604.las
reads.600.reads.601.las
reads.600.reads.602.las
reads.600.reads.603.las
reads.600.reads.604.las

(Meaning the files are still left after the run AND they are not mentioned for removal in the script produced).

**Comment by thegenemyers** [comment]
Hi German,

    I believe I have fixed this (and the previous case of no .las 
extension.  HPC.REPmask is
hopefully now good to go.  Checked in the patched code.

    -- Gene
