### ISSUE TITLE
Segfault when running datander

### ISSUE THREAD

**Issue by isovic** [thegenemyers/DAMASKER#8]
Hi Gene,

I was running `datander` and I ran into a segfault.
After some experimentation and profiling the code using Valgrind, I found that these lines are causing the crash:
https://github.com/thegenemyers/DAMASKER/blob/master/tandem.c#L923-L924

There are no boundary checks here to make sure `data->end > 0` and `data->beg >= Kmer`. After checking the values,  this is indeed what happens in some cases.

Best regards,
Ivan.

**Comment by thegenemyers** [comment]
This was due to running a stale version of datander.  Updating to the latest version solved it.
